# linear algebra for machine learning

### vectors and dot products

In [1]:
import numpy as np

In [2]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
print(array1,array2)


[1 2 3] [4 5 6]


### dot product

In [3]:
print(np.dot(array1,array2))

32


### matrices and operation(2D)

In [4]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(A,"\n",B)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]


### addition and substraction

In [5]:
print("A+B \n",A+B)

A+B 
 [[ 6  8]
 [10 12]]


In [6]:
print("A-B \n",A-B)


A-B 
 [[-4 -4]
 [-4 -4]]


### multilpication and division elementwise

In [7]:
print(A,"\n",B)
print("A*B \n",A*B)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]
A*B 
 [[ 5 12]
 [21 32]]


In [8]:
print(A,"\n",B)

print("A/B \n",A/B)

[[1 2]
 [3 4]] 
 [[5 6]
 [7 8]]
A/B 
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])
d=np.array([[7,8,4],[9,10,3],[11,12,13]])
print(c,"\n",d)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 [[ 7  8  4]
 [ 9 10  3]
 [11 12 13]]


In [10]:
print(c+d)

[[ 8 10  7]
 [13 15  9]
 [18 20 22]]


In [11]:
print(c-d)

[[-6 -6 -1]
 [-5 -5  3]
 [-4 -4 -4]]


In [12]:
print(c*d)

[[  7  16  12]
 [ 36  50  18]
 [ 77  96 117]]


In [13]:
print(c/d)

[[0.14285714 0.25       0.75      ]
 [0.44444444 0.5        2.        ]
 [0.63636364 0.66666667 0.69230769]]


### dot product of 2d array

In [14]:
print(A@B)

[[19 22]
 [43 50]]


In [15]:
print(array1@array2)

32


In [16]:
print(c)
print(d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 7  8  4]
 [ 9 10  3]
 [11 12 13]]


In [17]:
print(c@d)

[[ 58  64  49]
 [139 154 109]
 [220 244 169]]


In [18]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### transpose of matrix

In [19]:
print(A)

[[1 2]
 [3 4]]


In [20]:
print(A.T)

[[1 3]
 [2 4]]


In [21]:
print(c.T)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


### identity matrix

In [22]:
I=np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### inverse of matrix 2 by 2

In [23]:
a_inv=np.linalg.inv(A)
print(A)
print(a_inv)

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [24]:
F=np.array([[2,3,4],[1,4,3],[2,4,2]])
print(F)

[[2 3 4]
 [1 4 3]
 [2 4 2]]


In [25]:
print(F)
a_inv=np.linalg.inv(F)
print(a_inv)

[[2 3 4]
 [1 4 3]
 [2 4 2]]
[[ 0.33333333 -0.83333333  0.58333333]
 [-0.33333333  0.33333333  0.16666667]
 [ 0.33333333  0.16666667 -0.41666667]]


In [26]:
a_det=np.linalg.det(F)
print(F)
print(a_det)

[[2 3 4]
 [1 4 3]
 [2 4 2]]
-12.0


In [27]:
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
print(c)
b1=np.linalg.det(c)
print(b1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.66133814775094e-16


### Eigen values and vectors

In [29]:
eigenvalues,eigenvectors=np.linalg.eig(F)
print(F)
print("\nEigen values:")
print(eigenvalues)
print("\nEigen vectors:")
print(eigenvectors)

[[2 3 4]
 [1 4 3]
 [2 4 2]]

Eigen values:
[ 8.18740177  1.12056692 -1.30796869]

Eigen vectors:
[[-0.62508549 -0.8680815  -0.61416008]
 [-0.54770961  0.46949679 -0.29743818]
 [-0.55613156 -0.16126769  0.73098422]]


### Determinant of 3 by 3 

In [30]:
H=np.array([[1,4,7],[2,5,8],[3,6,2]])
print(H)

[[1 4 7]
 [2 5 8]
 [3 6 2]]


In [31]:
h_det=np.linalg.det(H)
print(h_det)

21.0
