In [1]:
import numpy as np

In [2]:
array=np.array([1,2,3,4,5,6])

In [3]:
print(array)

[1 2 3 4 5 6]


In [23]:
print(array.shape)

(6,)


#### 2D array

In [3]:
darray=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [4]:
print(darray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### To find out shape of an array

In [26]:
print(darray.shape)

(3, 3)


#### To find out the dimension of array

In [27]:
print(darray.ndim)

2


#### 3D array

In [28]:
arrayy=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [29]:
print(arrayy)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [30]:
print(arrayy.ndim)

3


#### to find out size of array

In [31]:
print(arrayy.size)

9


In [32]:
print(array.size)

6


#### To access single element from an array

In [33]:
print(array[1])

2


#### slicing of an array

In [34]:
print(array[2:5])

[3 4 5]


In [35]:
print(darray[0:2,1])

[2 5]


#### Reshape the array

In [36]:
array=np.array([1,2,3,4,5,6])

In [37]:
arrrr=array.reshape(2,3)
print(arrrr)

[[1 2 3]
 [4 5 6]]


In [38]:
darray=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(darray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### To find out the data type of an array

In [39]:
print(array.dtype)

int64


#### Access single element from an array

In [40]:
print(array[3])

4


#### Access single element from an multidimensional array

In [41]:
print(darray)
print(darray[0,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


#### Update the existing array

In [42]:
print(array)
array[3]=44
print(array)

[1 2 3 4 5 6]
[ 1  2  3 44  5  6]


#### Slicing the multi-dimensional array

In [43]:
print(darray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(darray[0:3])

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
print(darray[:,:2])

[[1 2]
 [4 5]
 [7 8]]


In [46]:
print(darray[:2])

[[1 2 3]
 [4 5 6]]


#### Addition of array

In [47]:
import numpy as np
a1 =np.array([3,4,5])
a2 =np.array([6,7,8])
print(a1)
print(a2)
print("addition of array:",a1+a2)

[3 4 5]
[6 7 8]
addition of array: [ 9 11 13]


In [48]:
a1 =np.array([33,44,55])
a2 =np.array([6,7,8])
print(a1)
print(a2)
print("substraction of array:",a1-a2)

[33 44 55]
[6 7 8]
substraction of array: [27 37 47]


In [49]:
a1 =np.array([[33,44,55],[6,7,8]])
a2 =np.array([[6,7,8],[3,8,4]])
print(a1)
print(a2)
print("multilpication of array:\n", a1*a2)

[[33 44 55]
 [ 6  7  8]]
[[6 7 8]
 [3 8 4]]
multilpication of array:
 [[198 308 440]
 [ 18  56  32]]


In [50]:
a1 =np.array([3,7,8])
a2 =np.array([3,7,8])
print(a1)
print(a2)
print("division of array:",a1/a2)

[3 7 8]
[3 7 8]
division of array: [1. 1. 1.]


In [51]:
arrayy=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arrayy)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [52]:
print(arrayy[0:1,:,:])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [53]:
arr1=np.array([1,2,3,4,5,6,7,8,9,10])
for i in arr1:
    if i %2==0:
        print(i,"is even")
    else:
        print(i," is odd")
        
        

1  is odd
2 is even
3  is odd
4 is even
5  is odd
6 is even
7  is odd
8 is even
9  is odd
10 is even


#### sum of an array

In [54]:
print(arr1.sum())

55


In [55]:
total=0
for i in arr1:
    print(f"adding {i} in {total}")
    total=total+i
print("tha final addition is ",total)    

adding 1 in 0
adding 2 in 1
adding 3 in 3
adding 4 in 6
adding 5 in 10
adding 6 in 15
adding 7 in 21
adding 8 in 28
adding 9 in 36
adding 10 in 45
tha final addition is  55


In [56]:
import numpy as np
ar1=np.array([12,65,99,88,70])
highest=ar1[0]
for n in ar1:
    if n>highest:
        highest=n
print(f"{highest} is greater")       

99 is greater


#### min of an array

In [57]:
import numpy as np
ar1=np.array([12,65,39,88,70])
greater=ar1[0]
for ele in ar1:
    if ele >=greater:
     greater=ele
print(greater)

88


In [58]:
min=ar1[0]
for ele in ar1:
    if ele <=min:
     min=ele
print(min)


12


#### minimum and maximum values from an array

In [59]:
import numpy as np
array1 =np.array([43,33,67,88,24])
print(array1)

[43 33 67 88 24]


In [62]:
high=array1[0]
for element in array1:
    if element>=high:
        high=element
print(high)        

88


In [61]:
arrayof2=np.array([[2,3,4],[6,7,8],[2,8,1]])
print(arrayof2)

[[2 3 4]
 [6 7 8]
 [2 8 1]]


#### create a function to find min max of an array

In [101]:
def array_max():
    array1 =([10,12,7])
    high=array1[0]
    for element in array1:
       if element > high:
         high = element
    print(high)  
array_max()

12


In [103]:
def array_min():
    array1 =([66,102,65,1,99])
    lowest=array1[0]
    for element in array1:
       if element < lowest:
         lowest = element
    print(lowest)  
array_min()

1


In [35]:
def countdown(i):
    while i>0:
        print(i)
        i-=1
print("happy new year")   
countdown(20)       

happy new year
20
19
18
17
16
15
14
13
12
11
10
9
8
7
6
5
4
3
2
1


In [19]:
def weekly_days(Day,Temp):
         print("weekly temperature:")
         for day,temp in zip(Day,Temp):
             print(f"{day}:{temp}\u00B0C")
        
         max_temp=max(Temp)
         hottestday_index=Temp.index(max_temp)
         hottest_day=Day[hottestday_index]
         print("\n",f"the hottest day is {hottest_day} with { max_temp}\u00B0C")
         
         min_temp=min(Temp)
         coldestday_index=Temp.index(min_temp)
         coldest_day=Day[coldestday_index]
         print(f"the coldest day is {coldest_day} with { min_temp}\u00B0C")

Day=["Mon","Tue","Wed","Thu","Fri","Sat","Sun"]
Temp=[30,32,47,40,39,27,47]    
weekly_days(Day,Temp)
        

weekly temperature:
Mon:30°C
Tue:32°C
Wed:47°C
Thu:40°C
Fri:39°C
Sat:27°C
Sun:47°C

 the hottest day is Wed with 47°C
the coldest day is Sat with 27°C


In [20]:
import pandas as pd
weather_data={"Day":["Mon","Tue","Wed","Thu","Fri","Sat","Sun"],
              "Temp":[30,32,47,40,39,27,47],
              "humidity":[70,65,70,68,72,65,73]
               }
df=pd.DataFrame(weather_data)
def hottestday(weather_data):
    high=weather_data["Temp"]
    for ele in weather_data["Temp"]:
        if ele > high:
            high=ele
    print(high)    
print("weekely weather data:","\n",df)

hottestday(weather_data)

weekely weather data: 
    Day  Temp  humidity
0  Mon    30        70
1  Tue    32        65
2  Wed    47        70
3  Thu    40        68
4  Fri    39        72
5  Sat    27        65
6  Sun    47        73


TypeError: '>' not supported between instances of 'int' and 'list'